import type { Metadata } from "next";
import "./globals.css";
import "./pico.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
        <div className="flex-grow p-5">{children}</div>
      </body>
    </html>
  );
}
